src/Entity/Commande.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use App\Repository\CommandeRepository;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Membre::class, inversedBy: 'commandes')]
    private $id_membre;

    #[ORM\ManyToOne(targetEntity: Produit::class, inversedBy: 'commandes')]
    private $id_produit;

    #[ORM\Column(type: 'integer')]
    #[Assert\GreaterThan(value: 0)]
    private $quantite;

    #[ORM\Column(type: 'float')]
    #[Assert\GreaterThanOrEqual(value: 0)]
    private $montant;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Choice(callback: 'choixEtat')]
    private $etat;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type('datetime')]
    private $date_enregistrement;


    
    public function __construct()
    {
        $tz = new \DateTimeZone('Europe/Paris');
        $now = new \DateTime();
        $now->setTimezone($tz);
        $this->setDateEnregistrement($now);
    }

    public function choixEtat(): array
    {
        return ['En cours', 'Envoyé', 'Livré'];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdMembre(): ?Membre
    {
        return $this->id_membre;
    }

    public function setIdMembre(?Membre $id_membre): self
    {
        $this->id_membre = $id_membre;

        return $this;
    }

    public function getIdProduit(): ?Produit
    {
        return $this->id_produit;
    }

    public function setIdProduit(?Produit $id_produit): self
    {
        $this->id_produit = $id_produit;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }
}

templates/commande/_delete_form.html.twig
<form method="post" action="{{ path('commande_delete', {'id': commande.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette commande ?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
	<button class="btn btn-outline-danger btn-sm float-start me-3">Supprimer</button>
</form>

templates/commande/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-success btn-sm float-end ms-3">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/commande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Commande{% endblock %}

{% block body %}
	<main class="container-fluid">
		<article class="container">
			<h1 class="text-center mb-4 fw-semibold fs-2">Modifier Commande</h1>
			{{ include('commande/_form.html.twig', {'button_label': 'Update'}) }}
			<a href="{{ path('commande_index') }}" class="btn btn-outline-primary btn-sm float-end ms-3">Retour</a>
			{{ include('commande/_delete_form.html.twig') }}
		</article>
	</main>
{% endblock %}

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Commandes{% endblock %}

{% block body %}
	<main class="container-fluid">
		<h1 class="text-center mb-4 fw-semibold fs-2">Commandes</h1>
		<div class="overflow-scroll">
			<table class="table table-sm table-hover px-5">
				<thead>
					<tr class="table-danger text-center align-middle">
						<th>#</th>
						<th>Membre</th>
						<th>Produit</th>
						<th>Quantite</th>
						<th>Montant</th>
						<th>Etat</th>
						<th>Options</th>
					</tr>
				</thead>
				<tbody>
					{% for commande in commandes %}
						<tr class="text-center align-middle">
							<td>{{ commande.id }}</td>
							<td>{{ commande.idMembre.id ~ ": " ~ commande.idMembre.pseudo }}</td>
							<td>{{ commande.idProduit.id ~ ": " ~ commande.idProduit.titre ~ " (" ~ commande.idProduit.prix|deviseFr ~ "/pièce)" }}<br>
								<img src="/upload{{ asset(commande.idProduit.photo) }}" alt="Photo du produit {{ commande.idProduit.description }}" class="img-fluid img-thumbnail" style="max-height: 150px;">
							</td>
							<td>{{ commande.quantite }}</td>
							<td>{{ commande.montant|deviseFr }}</td>
							<td>{{ commande.etat }}</td>
							<td>
								{% include 'commun/action.html.twig' with {'id': commande.id, 'show': 'commande_show', 'edit': 'commande_edit', 'delete': 'commande_delete'} %}
							</td>
						</tr>
					{% else %}
						<tr class="text-center align-middle">
							<td colspan="7">Aucune commande</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<a href="{{ path('commande_new') }}" class="btn btn-outline-primary btn-sm float-end ms-3">Ajouter</a>
	</main>
{% endblock %}

templates/commande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Commande{% endblock %}

{% block body %}
	<main class="container-fluid">
		<article class="container">
			<h1 class="text-center mb-4 fw-semibold fs-2">Ajouter Commande</h1>
			{{ include('commande/_form.html.twig') }}
			<a href="{{ path('commande_index') }}" class="btn btn-outline-primary btn-sm float-end ms-3">Retour</a>
		</article>
	</main>
{% endblock %}

templates/commande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
	<main class="container-fluid">
		<article class="container">
			<h1 class="text-center mb-4 fw-semibold fs-2">Commande</h1>
			<table class="table table-sm">
				<tbody>
					<tr>
						<th>#</th>
						<td>{{ commande.id }}</td>
					</tr>
					<tr>
						<th># Produit</th>
						<td>{{ commande.idProduit.id }}</td>
					</tr>
					<tr>
						<th># Membre</th>
						<td>{{ commande.idMembre.id }}</td>
					</tr>
					<tr>
						<th>Quantite</th>
						<td>{{ commande.quantite }}</td>
					</tr>
					<tr>
						<th>Montant</th>
						<td>{{ commande.montant|deviseFr }}</td>
					</tr>
					<tr>
						<th>Etat</th>
						<td>{{ commande.etat }}</td>
					</tr>
					<tr>
						<th>Date Enregistrement</th>
						<td>{{ commande.dateEnregistrement ? commande.dateEnregistrement|date('Y-m-d H:i') : '' }}</td>
					</tr>
				</tbody>
			</table>
			<a href="{{ path('commande_index') }}" class="btn btn-outline-primary btn-sm float-end ms-3">Retour</a>
			<a href="{{ path('commande_edit', {'id': commande.id}) }}" class="btn btn-outline-primary btn-sm float-end mx-1">Modifier</a>
			{{ include('commande/_delete_form.html.twig') }}
		</article>
	</main>
{% endblock %}